/**
 * Board Routes — Phase 3
 *
 * CRUD operations for whiteboard boards plus collaborator management.
 * All routes are protected by the auth middleware — the authenticated
 * user's ID is read from `req.user.userId`.
 */

const express = require('express');
const Board = require('../models/Board');
const User = require('../models/User');
const authMiddleware = require('../middleware/auth');

const router = express.Router();

// Apply authentication to every route in this router
router.use(authMiddleware);

// ---------------------------------------------------------------------------
// POST /api/boards
// Create a new board. The roomId is auto-generated by the Board model.
// Body (optional): { title }
// ---------------------------------------------------------------------------
router.post('/', async (req, res) => {
  try {
    const { title } = req.body;

    const board = await Board.create({
      title: title || 'Untitled Board',
      owner: req.user.userId,
    });

    return res.status(201).json(board);
  } catch (err) {
    console.error('[Boards] Create error:', err.message);
    return res.status(500).json({ error: 'Failed to create board.' });
  }
});

// ---------------------------------------------------------------------------
// GET /api/boards
// List all boards the user owns OR is a collaborator on, newest first.
// ---------------------------------------------------------------------------
router.get('/', async (req, res) => {
  try {
    const userId = req.user.userId;

    const boards = await Board.find({
      $or: [{ owner: userId }, { 'collaborators.user': userId }],
    })
      .sort({ updatedAt: -1 })
      .lean();

    return res.json(boards);
  } catch (err) {
    console.error('[Boards] List error:', err.message);
    return res.status(500).json({ error: 'Failed to fetch boards.' });
  }
});

// ---------------------------------------------------------------------------
// GET /api/boards/:roomId
// Fetch a single board by its shareable roomId (used for join-by-link).
// ---------------------------------------------------------------------------
router.get('/:roomId', async (req, res) => {
  try {
    const board = await Board.findOne({ roomId: req.params.roomId }).lean();

    if (!board) {
      return res.status(404).json({ error: 'Board not found.' });
    }

    return res.json(board);
  } catch (err) {
    console.error('[Boards] Fetch error:', err.message);
    return res.status(500).json({ error: 'Failed to fetch board.' });
  }
});

// ---------------------------------------------------------------------------
// PUT /api/boards/:roomId/role
// Add or update a collaborator's role on a board.
// Body: { email, role }
// Only the board owner can modify collaborator roles.
// ---------------------------------------------------------------------------
router.put('/:roomId/role', async (req, res) => {
  try {
    const { email, role } = req.body;

    // Validate required fields
    if (!email || !role) {
      return res.status(400).json({ error: 'Email and role are required.' });
    }

    // Validate role value
    if (!['editor', 'viewer'].includes(role)) {
      return res.status(400).json({ error: 'Role must be "editor" or "viewer".' });
    }

    // Find the board
    const board = await Board.findOne({ roomId: req.params.roomId });
    if (!board) {
      return res.status(404).json({ error: 'Board not found.' });
    }

    // Only the owner can manage collaborators
    if (board.owner.toString() !== req.user.userId) {
      return res.status(403).json({ error: 'Only the board owner can manage collaborators.' });
    }

    // Look up the target user by email
    const targetUser = await User.findOne({ email: email.toLowerCase().trim() });
    if (!targetUser) {
      return res.status(404).json({ error: 'User not found with that email.' });
    }

    // Cannot add the owner as a collaborator
    if (targetUser._id.toString() === board.owner.toString()) {
      return res.status(400).json({ error: 'Cannot add the board owner as a collaborator.' });
    }

    // Check if the user is already a collaborator — update role if so
    const existing = board.collaborators.find(
      (c) => c.user.toString() === targetUser._id.toString()
    );

    if (existing) {
      existing.role = role;
    } else {
      board.collaborators.push({ user: targetUser._id, role });
    }

    await board.save();

    return res.json(board);
  } catch (err) {
    console.error('[Boards] Role update error:', err.message);
    return res.status(500).json({ error: 'Failed to update collaborator role.' });
  }
});

// ---------------------------------------------------------------------------
// DELETE /api/boards/:roomId/collaborator/:userId
// Remove a collaborator from a board. Only the board owner can do this.
// ---------------------------------------------------------------------------
router.delete('/:roomId/collaborator/:userId', async (req, res) => {
  try {
    const board = await Board.findOne({ roomId: req.params.roomId });
    if (!board) {
      return res.status(404).json({ error: 'Board not found.' });
    }

    // Only the owner can remove collaborators
    if (board.owner.toString() !== req.user.userId) {
      return res.status(403).json({ error: 'Only the board owner can remove collaborators.' });
    }

    // Filter out the target collaborator
    const initialLength = board.collaborators.length;
    board.collaborators = board.collaborators.filter(
      (c) => c.user.toString() !== req.params.userId
    );

    if (board.collaborators.length === initialLength) {
      return res.status(404).json({ error: 'Collaborator not found on this board.' });
    }

    await board.save();

    return res.json(board);
  } catch (err) {
    console.error('[Boards] Remove collaborator error:', err.message);
    return res.status(500).json({ error: 'Failed to remove collaborator.' });
  }
});

// ---------------------------------------------------------------------------
// GET /api/boards/:roomId/collaborators
// List all collaborators for a board with populated user info.
// ---------------------------------------------------------------------------
router.get('/:roomId/collaborators', async (req, res) => {
  try {
    const board = await Board.findOne({ roomId: req.params.roomId })
      .populate('collaborators.user', 'username email')
      .populate('owner', 'username email')
      .lean();

    if (!board) {
      return res.status(404).json({ error: 'Board not found.' });
    }

    return res.json({
      owner: board.owner,
      collaborators: board.collaborators,
    });
  } catch (err) {
    console.error('[Boards] List collaborators error:', err.message);
    return res.status(500).json({ error: 'Failed to fetch collaborators.' });
  }
});

// ---------------------------------------------------------------------------
// DELETE /api/boards/:roomId
// Delete a board and all associated data. Only the owner can delete.
// ---------------------------------------------------------------------------
router.delete('/:roomId', async (req, res) => {
  try {
    const board = await Board.findOne({ roomId: req.params.roomId });

    if (!board) {
      return res.status(404).json({ error: 'Board not found.' });
    }

    // Only the owner can delete
    if (board.owner.toString() !== req.user.userId) {
      return res.status(403).json({ error: 'Only the board owner can delete it.' });
    }

    // Delete associated data
    const Stroke = require('../models/Stroke');
    const StickyNote = require('../models/StickyNote');
    const ChatMessage = require('../models/ChatMessage');

    await Promise.all([
      Stroke.deleteMany({ boardId: board._id }),
      StickyNote.deleteMany({ boardId: board._id }),
      ChatMessage.deleteMany({ boardId: board._id }),
    ]);

    // Delete the board itself
    await Board.deleteOne({ _id: board._id });

    return res.json({ message: 'Board deleted successfully.' });
  } catch (err) {
    console.error('[Boards] Delete error:', err.message);
    return res.status(500).json({ error: 'Failed to delete board.' });
  }
});

module.exports = router;
